# Generated by Django 5.0.2 on 2024-02-21 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0003_alter_paciente_cns_alter_paciente_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prontuario',
            name='anotacoes',
            field=models.TextField(blank=True),
        ),
    ]
