# Generated by Django 5.0.2 on 2024-02-21 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0004_alter_prontuario_anotacoes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='prescricoes',
        ),
        migrations.AlterField(
            model_name='consulta',
            name='data_consulta',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
