# Generated by Django 5.0.2 on 2024-02-21 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0005_remove_consulta_prescricoes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoExame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('qr_code', models.TextField(blank=True, null=True)),
                ('prontuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_exames', to='paciente.prontuario')),
            ],
        ),
    ]
