# Generated by Django 5.0.2 on 2024-02-28 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0007_arquivo_prontuario_arquivos'),
    ]

    operations = [
        migrations.CreateModel(
            name='CID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='exame',
            name='arquivo',
        ),
        migrations.RemoveField(
            model_name='exame',
            name='data_exame',
        ),
        migrations.RemoveField(
            model_name='exame',
            name='prontuario',
        ),
        migrations.RemoveField(
            model_name='exame',
            name='tipo_exame',
        ),
        migrations.AddField(
            model_name='exame',
            name='nome',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consulta',
            name='cids',
            field=models.ManyToManyField(blank=True, related_name='consultas_cids', to='paciente.cid'),
        ),
        migrations.AddField(
            model_name='exame',
            name='cids_comuns',
            field=models.ManyToManyField(related_name='exames_comuns', to='paciente.cid'),
        ),
    ]
