# Generated by Django 5.0.2 on 2024-02-29 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0008_cid_remove_exame_arquivo_remove_exame_data_exame_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivo',
            name='solicitacao_exame',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='paciente.solicitacaoexame'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ItemSolicitacaoExame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='prontuarios/')),
                ('exame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.exame')),
                ('solicitacao_exame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='paciente.solicitacaoexame')),
            ],
        ),
    ]
