# Generated by Django 5.0.2 on 2024-03-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0009_arquivo_solicitacao_exame_itemsolicitacaoexame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaoexame',
            name='descricao',
            field=models.TextField(blank=True),
        ),
    ]
