# Generated by Django 5.0.2 on 2024-02-21 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profissional', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissionalsaude',
            name='cpf',
            field=models.CharField(max_length=11, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profissionalsaude',
            name='data_nascimento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='profissionalsaude',
            name='nome',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profissionalsaude',
            name='registro_profissional',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
